user root;
worker_processes 1;

events {    
}

http {
    server {
        listen 80;

        server_name 193.108.113.5; #change to server ip

        location / {
            proxy_pass http://front:8080/;
        }

        location /api/ {
            proxy_pass http://web:8000/;
        }
    }
}