FROM python:alpine3.22

WORKDIR /app/back

COPY config.py requirements.txt alembic.ini ./

RUN pip install -r ./requirements.txt && \
    pip install uvicorn[standard]

COPY . .

CMD [ "python3", "main.py"]