"""Add ondelete for foreign key in token

Revision ID: dd9768fb9451
Revises: d4c74ee08a03
Create Date: 2026-04-02 15:46:19.911585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd9768fb9451'
down_revision: Union[str, Sequence[str], None] = 'd4c74ee08a03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('tokens_user_id_fkey'), 'tokens', type_='foreignkey')
    op.create_foreign_key(None, 'tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tokens', type_='foreignkey')
    op.create_foreign_key(op.f('tokens_user_id_fkey'), 'tokens', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
