"""remove uniqueness of post_id in file

Revision ID: 582e99ba4098
Revises: 9fe8dc5659a8
Create Date: 2026-03-02 21:02:07.448900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '582e99ba4098'
down_revision: Union[str, Sequence[str], None] = '9fe8dc5659a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_files_type'), table_name='files')
    op.create_index(op.f('ix_files_type'), 'files', ['type'], unique=False)
    op.create_unique_constraint(None, 'files', ['url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'files', type_='unique')
    op.drop_index(op.f('ix_files_type'), table_name='files')
    op.create_index(op.f('ix_files_type'), 'files', ['type'], unique=True)
    # ### end Alembic commands ###
