"""remove uniqueness of post_id in file

Revision ID: 9fe8dc5659a8
Revises: 6d91798695b7
Create Date: 2026-03-02 20:55:10.321448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fe8dc5659a8'
down_revision: Union[str, Sequence[str], None] = '6d91798695b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_files_post_id'), table_name='files')
    op.create_index(op.f('ix_files_post_id'), 'files', ['post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_files_post_id'), table_name='files')
    op.create_index(op.f('ix_files_post_id'), 'files', ['post_id'], unique=True)
    # ### end Alembic commands ###
