"""Add all models

Revision ID: ec1140e5d269
Revises: 
Create Date: 2026-02-12 19:18:46.283407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec1140e5d269'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groupes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_groupes_id'), 'groupes', ['id'], unique=False)
    op.create_table('themes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_themes_name'), 'themes', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('nickname', sa.String(length=15), nullable=False),
    sa.Column('role', sa.String(length=7), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('avatar_url', sa.String(length=120), nullable=False),
    sa.Column('desctiption', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('password')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_nickname'), 'users', ['nickname'], unique=True)
    op.create_table('posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('creation_time', sa.DateTime(), nullable=False),
    sa.Column('updating_time', sa.DateTime(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('author_id')
    )
    op.create_index(op.f('ix_posts_creation_time'), 'posts', ['creation_time'], unique=False)
    op.create_index(op.f('ix_posts_id'), 'posts', ['id'], unique=False)
    op.create_table('users_in_group',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('groupe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['groupe_id'], ['groupes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'groupe_id')
    )
    op.create_index(op.f('ix_users_in_group_groupe_id'), 'users_in_group', ['groupe_id'], unique=False)
    op.create_index(op.f('ix_users_in_group_user_id'), 'users_in_group', ['user_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('creation_time', sa.DateTime(), nullable=False),
    sa.Column('updating_time', sa.DateTime(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_author_id'), 'comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_comments_creation_time'), 'comments', ['creation_time'], unique=False)
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.create_index(op.f('ix_comments_post_id'), 'comments', ['post_id'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(length=30), nullable=False),
    sa.Column('type', sa.String(length=7), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_files_post_id'), 'files', ['post_id'], unique=True)
    op.create_index(op.f('ix_files_type'), 'files', ['type'], unique=True)
    op.create_table('posts_in_group',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groupes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'group_id')
    )
    op.create_index(op.f('ix_posts_in_group_group_id'), 'posts_in_group', ['group_id'], unique=False)
    op.create_index(op.f('ix_posts_in_group_post_id'), 'posts_in_group', ['post_id'], unique=False)
    op.create_table('themes_in_post',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('theme_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'theme_id')
    )
    op.create_index(op.f('ix_themes_in_post_post_id'), 'themes_in_post', ['post_id'], unique=False)
    op.create_index(op.f('ix_themes_in_post_theme_id'), 'themes_in_post', ['theme_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_themes_in_post_theme_id'), table_name='themes_in_post')
    op.drop_index(op.f('ix_themes_in_post_post_id'), table_name='themes_in_post')
    op.drop_table('themes_in_post')
    op.drop_index(op.f('ix_posts_in_group_post_id'), table_name='posts_in_group')
    op.drop_index(op.f('ix_posts_in_group_group_id'), table_name='posts_in_group')
    op.drop_table('posts_in_group')
    op.drop_index(op.f('ix_files_type'), table_name='files')
    op.drop_index(op.f('ix_files_post_id'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_comments_post_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_creation_time'), table_name='comments')
    op.drop_index(op.f('ix_comments_author_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_users_in_group_user_id'), table_name='users_in_group')
    op.drop_index(op.f('ix_users_in_group_groupe_id'), table_name='users_in_group')
    op.drop_table('users_in_group')
    op.drop_index(op.f('ix_posts_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_creation_time'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_users_nickname'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_themes_name'), table_name='themes')
    op.drop_table('themes')
    op.drop_index(op.f('ix_groupes_id'), table_name='groupes')
    op.drop_table('groupes')
    # ### end Alembic commands ###
