"""add attributes for token

Revision ID: 4d324e38737a
Revises: 6ecee9dc31ac
Create Date: 2026-03-15 00:12:01.040502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d324e38737a'
down_revision: Union[str, Sequence[str], None] = '6ecee9dc31ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('tokens', sa.Column('expired_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokens', 'expired_at')
    op.drop_column('tokens', 'is_active')
    # ### end Alembic commands ###
