"""description nullable

Revision ID: 9c5b80066619
Revises: d92114ec496e
Create Date: 2026-02-24 16:13:00.506876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c5b80066619'
down_revision: Union[str, Sequence[str], None] = 'd92114ec496e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('description', sa.Text(), nullable=True))
    op.drop_column('users', 'desctiption')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('desctiption', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('users', 'description')
    # ### end Alembic commands ###
