"""server_default for activity in User

Revision ID: 749ac1d7bb2f
Revises: 57d9b1ff7335
Create Date: 2026-02-24 16:19:01.451663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '749ac1d7bb2f'
down_revision: Union[str, Sequence[str], None] = '57d9b1ff7335'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
