"""unset uniqness of author_id

Revision ID: 6d91798695b7
Revises: 757bfdd12faa
Create Date: 2026-02-24 16:43:22.310848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d91798695b7'
down_revision: Union[str, Sequence[str], None] = '757bfdd12faa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('posts_author_id_key'), 'posts', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('posts_author_id_key'), 'posts', ['author_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
